#!/usr/bin/env bash
# send file

if [[ $# -lt 4 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	#scp "$1" -i "$4" "$3"@"$2":~/
	echo scp -i "$4" "$1" "$3"@"$2":~/
fi
