#!/usr/bin/env bash
# set up nginx

apt-get update
apt-get -y install nginx

service nginx start

sed -i 's/try_files $uri $uri\/ =404;/return 200 "Hello World!\\n";/' /etc/nginx/sites-available/default

service nginx restart
