#!/usr/bin/env bash
# install and configure haproxy
sudo apt-get update
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy=2.8.\*

sudo cp -a /etc/haproxy/haproxy.cfg{,.first_copy}

printf "\n\nfrontend ty-frontend\n" | sudo tee -a /etc/haproxy/haproxy.cfg
printf "\tbind *:80\n\tmode http\n\tdefault_backend ty-backend\n" | sudo tee -a /etc/haproxy/haproxy.cfg
printf "backend ty-backend\n" | sudo tee -a /etc/haproxy/haproxy.cfg
printf "\tbalance roundrobin\n\tserver web-01 34.227.91.204:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
printf "\tserver web-02 18.207.139.28:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg

printf "\nENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
