#!/usr/bin/env bash
# controlling signals and processes

echo "$$" > /var/run/myscript.pid

while :; do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" TERM
	trap "echo 'Y U no love me?!'" INT
	trap "rm /var/run/myscript.pid; exit" QUIT
done

