#!/usr/bin/env bash
# managing a process

if [[ $# -lt 0 || -z "$(echo $1 | grep -E 'start|stop|restart')" ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
	"start")
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	
	"stop")
		kill -9 "$(pgrep -f 'manage_my_process')"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	
	"restart")
		kill -9 -f "manage_my_process stop"
		rm /var/run/my_process.pid
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
esac
