#!/usr/bin/env bash
# managing a process

if [[ "$#" -lt 0 ]]; then
	echo "Usage: manage_my_process {start|stop|restart}"
	exit
fi

case "$1" in
	"start")
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	
	"stop")
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		pkill -9 -f "manage_my_process"
		;;
	
	"restart")
		pkill -9 -f "./manage_my_process"
		rm /var/run/my_process.pid
		./manage_my_process &
		echo "$$" > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;

	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
