#!/usr/bin/env bash
# story about passwd file

IFS=":"
while read -r user pass user_id grp_id u_id_info home cmd_shell; do
	echo "The user $user is part of the $grp_id gang, lives in $home and rides $cmd_shell. $user_id's place is protected by the passcode $pass, more info about the user here: $u_id_info"
done < "/etc/passwd"
