#!/usr/bin/env bash
# display clock time

hour=0
min=0
while [ $hour -le 11 ]; do
	if [[ $min -eq 59 ]]; then
		hour=$((hour + 1))
		min=0
	fi
	if [[ $min -eq 0 ]]; then
		echo "Hour: $hour"
	fi
	min=$((min + 1))
	if [[ $hour -ne 12 ]]; then
		echo $min
	fi
done
